# Site settings
title: Maryjka.pl
description: Travel, photography, hairdresser
keywords: Travel, photography, hairdresser, blogging
author: Maryjka
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
